### ISSUE TITLE
this is a fishing bot, it collects money directly from your wallet

### ISSUE THREAD

**Issue by jank1n** [LogicPush/pump-fun-bump-bot#1]
this is a fishing bot, it collects money directly from your wallet check on solscan all your transactions and you will see there is a percentage going straight to dev

**Comment by LogicPush** [comment]
This is called fees. If I wanted to steal users, don't you think I'd rather suck up the entire wallet contents in one go? 

Poor spirit

**Comment by jank1n** [comment]
you didnt tell anyone about the fees you take. You said it is a free bot. You scammer, you have drained my whole wallet after several transactions. So yeah, it is stealing
